package com.example.universityapp.model

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "students")                    // table name is 'students'
data class Student (val firstName : String,              // in program we will refer table name by 'Student'
                    val lastName :  String,
                    val marks : Int,
                    @PrimaryKey(autoGenerate = true) val id : Int = 0 )   // default id is 0.. it is going to be autogenerated ie auto incremented if not given then from default